version: "3.1"

services:
  peppermint_postgres:
    container_name: peppermint_postgres
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: peppermint
    networks:
      - peppermint_network
    command: [ "postgres", "-c", "log_statement=all" ]

  peppermint:
    container_name: peppermint
    build: "."
    ports:
      - 3000:3000
      - 5003:5003
    restart: always
    depends_on:
      - peppermint_postgres
    healthcheck:
      test: [ "CMD", "sh", "-c", "wget --spider $$API_URL" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - peppermint_network
    environment:
      DB_USERNAME: "peppermint"
      DB_PASSWORD: "1234"
      DB_HOST: "peppermint_postgres"
      DATABASE_URL: "postgresql://peppermint:1234@localhost:5433/peppermint?schema=public"
      SECRET: 'peppermint4life'

volumes:
  pgdata:


networks:
  peppermint_network:
    name: peppermint_network
    driver: bridge
