version: "3.3"
services:
  pg:
    image: "postgres:11"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=pepppermint
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=peppermint
      - DATABASE_URL=postgresql://pepppermint:1234@localhost:5433/peppermint?schema=public
    container_name: "pg"
    ports:
      - '5433:5432'
    networks:
      - peppermint_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: jcalonso/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

volumes:
  postgres_data:


networks:
  peppermint_network:
    driver: bridge
    external: true
